### ISSUE TITLE
NGINX or Template output module

### ISSUE THREAD

**Issue by nyodas** [blablacar/go-synapse#3]
Add a module to output the backend into a file , possibly templated.

**Comment by n0rad** [comment]
use case ?

**Comment by n0rad** [comment]
I need a use cas to know how it should be implemented. as a new router, or as "log" of current router

**Comment by nyodas** [comment]
If i remember correctly 
it was to use the nginx router instead of haproxy to set up the upstream configuration directly in nginx.

**Comment by n0rad** [comment]
So it should probably be a new router implementation using nginx -> #12
